name: build-image
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout snapd
        uses: actions/checkout@v3
        with:
          repository: jhenstridge/snapd
          ref: desktop-mega-merge
          path: snapd
      - name: Get snapd revision
        id: snapd-get-rev
        run: |
          cd snapd
          echo "cache_key=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Cache snapd
        id: cache-snapd
        uses: actions/cache@v3
        with:
          path: ./snapd/*.snap
          key: ${{ steps.snapd-get-rev.outputs.cache_key }}
      #- name: Enale snapd experimental features
      #  run: |
      #    cd snapd
      #    patch -p1 < ../snapd-enable-features.patch
      - name: Build snapd
        if: steps.cache-snapd.outputs.cache-hit != 'true'
        uses: snapcore/action-build@v1
        with:
          path: ./snapd
          snapcraft-channel: 4.x/stable
      - name: Install build dependencies
        run: |
          sudo apt install -y make squashfs-tools dosfstools mtools
          sudo snap refresh --edge snapd
          sudo snap install --classic ubuntu-image
      - name: Build image
        run: |
          snapd_snap=$(ls snapd/snapd_*.snap)
          make EXTRA_SNAPS="$snapd_snap"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: |
            README.md
            *.img.gz
