name: build-image
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build core20-gdm
        uses: snapcore/action-build@v1
        id: snapcraft_base
        with:
          path: ./core20
      - name: Build ubuntu-desktop-session
        uses: snapcore/action-build@v1
        id: snapcraft_session
        with:
          path: ./ubuntu-desktop-session
      - name: Checkout snapd
        uses: actions/checkout@v2
        with:
          repository: jhenstridge/snapd
          ref: desktop-mega-merge
          path: snapd
      - name: Enale snapd experimental features
        run: |
          cd snapd
          patch -p1 < ../snapd-enable-features.patch
      - name: Build snapd
        uses: snapcore/action-build@v1
        id: snapcraft_snapd
        with:
          path: ./snapd
      - name: Install build dependencies
        run: |
          sudo apt install -y make squashfs-tools dosfstools mtools xz-utils
          sudo snap refresh --edge snapd
          sudo snap install --classic ubuntu-image
      - name: Build image
        run: make EXTRA_SNAPS="${{ steps.snapcraft_base.outputs.snap }} ${{ steps.snapcraft_session.outputs.snap }} ${{ steps.snapcraft_snapd.outputs.snap }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: |
            README.md
            *.img.xz
